export { default as Tabs } from './tabs.vue'
export { default as TabsList } from './tabsList.vue'
export { default as TabsTrigger } from './tabsTrigger.vue'
export { default as TabsContent } from './tabsContent.vue'
export { default as TabsExample } from './tabsExample.vue'